name: Upload Release Assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build release binary (musl)
        run: cargo build --release

      - name: Prepare asset
        run: |
          BIN=target/x86_64-unknown-linux-musl/release/client-hw-info
          OUT="client-hw-info-${{ github.event.release.tag_name }}-x86_64-unknown-linux-musl"
          cp "$BIN" "$OUT"
          chmod +x "$OUT"

      - name: Upload asset to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            client-hw-info-${{ github.event.release.tag_name }}-x86_64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_GITHUB_CLIENT_HW_TOOL }}